### ISSUE TITLE
Error on install & 1st use

### ISSUE THREAD

**Issue by scott-joe** [Matthew-Smith/atom-glowing-cursor#3]
``` error
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.) at line (9) column (2)
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.) at line (9) column (2)
    at /Users/scott.williams/.atom/packages/linter-eslint/lib/main.js:227:21
    at Array.map (native)
    at /Users/scott.williams/.atom/packages/linter-eslint/lib/main.js:192:27
```

**Comment by jdollar** [comment]
I believe this issue is from a different package linter-eslint. It looks like there is a similar issue out on their github that has been closed: https://github.com/AtomLinter/linter-eslint/issues/750. I don't believe this error is a issue with this package.

**Comment by Matthew-Smith** [comment]
As jdollar said I do not believe this to be an issue with the cursor package but with linter-eslint.  Please re-open the issue if we are incorrect.

**Comment by scott-joe** [comment]
Thanks all. In hindsight, I'm sorry I submitted this to you. Not entirely sure what in the editor made me think it was your lib's issue...but thanks for pointing me in the right direction. We use a custom .eslintrc based on airbnb's eslint and somewhere along those lines we have what would appear to be an outdated version of eslint causing errors. Thanks again.
