### ISSUE TITLE
Deprecated selector in `glowing-cursor/styles/index.atom-text-editor.less`

### ISSUE THREAD

**Issue by budnix** [Matthew-Smith/atom-glowing-cursor#5]
In `glowing-cursor/styles/index.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .cursors .cursor` => `atom-text-editor.editor .cursors .cursor`

* `atom-text-editor[mini]:not(.is-focused)::shadow .cursors .cursor` => `atom-text-editor[mini]:not(.is-focused).editor .cursors .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

PS: Great plugin, really like it 👍

**Comment by chrishough** [comment]
+1

**Comment by chrishough** [comment]
Thank you.
